from __future__ import annotations

from pathlib import Path
from typing import Any


SUPPORTED_RUNTIME_PROTOCOLS = {
    "dmr",
    "p25",
}


def _require_frequency(
    settings: dict[str, Any],
) -> int:
    frequency_hz = int(
        settings.get(
            "frequency_hz",
            0,
        )
    )

    if frequency_hz <= 0:
        raise ValueError(
            "Invalid RF frequency"
        )

    return frequency_hz


def _require_radio_id(
    settings: dict[str, Any],
) -> int:
    radio_id = int(
        settings.get(
            "radio_id",
            0,
        )
    )

    if radio_id <= 0:
        raise ValueError(
            "Radio ID must be greater than zero"
        )

    return radio_id


def _normalize_nac(
    value: Any,
) -> str:
    raw = str(
        value
    ).strip()

    if raw.lower().startswith(
        "0x"
    ):
        raw = raw[2:]

    try:
        nac = int(
            raw,
            16,
        )

    except ValueError as error:
        raise ValueError(
            f"Invalid P25 NAC: {value}"
        ) from error

    if (
        nac < 0
        or nac > 0xFFF
    ):
        raise ValueError(
            "P25 NAC must be between 000 and FFF"
        )

    return f"{nac:03X}"


def validate_runtime_mode(
    protocol: str,
    settings: dict[str, Any],
) -> None:
    protocol = (
        protocol
        .strip()
        .lower()
    )

    if protocol == "tetra":
        raise ValueError(
            "TETRA is not supported by the "
            "MMDVM-IQ backend"
        )

    if protocol == "fm":
        raise ValueError(
            "FM runtime mapping is not implemented yet. "
            "FM settings are still stored normally."
        )

    if protocol not in (
        SUPPORTED_RUNTIME_PROTOCOLS
    ):
        raise ValueError(
            f"Unsupported runtime protocol: "
            f"{protocol}"
        )

    _require_frequency(
        settings
    )

    _require_radio_id(
        settings
    )

    if protocol == "dmr":
        color_code = int(
            settings.get(
                "color_code",
                -1,
            )
        )

        if not 0 <= color_code <= 15:
            raise ValueError(
                "DMR Color Code must be "
                "between 0 and 15"
            )

        timeslot = int(
            settings.get(
                "timeslot",
                0,
            )
        )

        if timeslot not in (
            1,
            2,
        ):
            raise ValueError(
                "DMR Timeslot must be 1 or 2"
            )

    if protocol == "p25":
        _normalize_nac(
            settings.get(
                "nac",
                "",
            )
        )

        modulation = str(
            settings.get(
                "modulation",
                "",
            )
        ).strip().lower()

        if modulation != "c4fm":
            raise ValueError(
                "Current MMDVM-IQ P25 runtime "
                "supports the C4FM path only"
            )


def render_mmdvm_host_config(
    protocol: str,
    settings: dict[str, Any],
    *,
    callsign: str,
) -> str:
    protocol = (
        protocol
        .strip()
        .lower()
    )

    validate_runtime_mode(
        protocol,
        settings,
    )

    frequency_hz = (
        _require_frequency(
            settings
        )
    )

    radio_id = (
        _require_radio_id(
            settings
        )
    )

    dmr_enable = (
        1
        if protocol == "dmr"
        else 0
    )

    p25_enable = (
        1
        if protocol == "p25"
        else 0
    )

    dmr_id = radio_id

    dmr_color_code = int(
        settings.get(
            "color_code",
            1,
        )
    )

    p25_id = radio_id

    p25_nac = (
        _normalize_nac(
            settings.get(
                "nac",
                "293",
            )
        )
        if protocol == "p25"
        else "293"
    )

    runtime_comments: list[str] = [
        "# ------------------------------------------------------------",
        "# AUTO-GENERATED BY RF GATEWAY",
        "# DO NOT EDIT MANUALLY",
        "#",
        f"# Protocol: {protocol.upper()}",
        f"# Frequency from GUI: {frequency_hz} Hz",
    ]

    if protocol == "dmr":
        runtime_comments.extend(
            [
                (
                    "# Requested DMR Timeslot: "
                    f"{settings['timeslot']}"
                ),
                (
                    "# Requested DMR Talkgroup: "
                    f"{settings['talkgroup']}"
                ),
                (
                    "# Requested DMR Radio ID: "
                    f"{settings['radio_id']}"
                ),
            ]
        )

    if protocol == "p25":
        runtime_comments.extend(
            [
                (
                    "# Requested P25 NAC: "
                    f"{p25_nac}"
                ),
                (
                    "# Requested P25 Talkgroup: "
                    f"{settings['talkgroup']}"
                ),
                (
                    "# Requested P25 Radio ID: "
                    f"{settings['radio_id']}"
                ),
                (
                    "# Requested P25 Modulation: "
                    f"{settings['modulation']}"
                ),
            ]
        )

    runtime_comments.extend(
        [
            "# ------------------------------------------------------------",
            "",
        ]
    )

    body = f"""[General]
Callsign={callsign}
Id={radio_id}
Timeout=180
Duplex=0
Daemon=0

[Info]
Power=0
Latitude=0.0
Longitude=0.0
Height=0
Location=RF Gateway
Description=RF Gateway SXceiver
URL=

[Log]
DisplayLevel=2
FileLevel=0
MQTTLevel=1

[MQTT]
Host=127.0.0.1
Port=1883
Keepalive=60
Name=rf-gateway-mmdvm-host
Auth=0
Username=mmdvm
Password=mmdvm

[Remote Control]
Enable=1

[CW Id]
Enable=0
Time=10
Callsign={callsign}

[Modem]
Protocol=udp
ModemAddress=127.0.0.1
ModemPort=3334
LocalAddress=127.0.0.1
LocalPort=3335

RXFrequency={frequency_hz}
TXFrequency={frequency_hz}

RXInvert=1
TXInvert=1
PTTInvert=0

TXDelay=100
DMRDelay=0

RXOffset=0
TXOffset=0
RXDCOffset=0
TXDCOffset=0

RFLevel=100
RXLevel=83
TXLevel=83

Trace=0
Debug=0

[DMR]
Enable={dmr_enable}
Id={dmr_id}
ColorCode={dmr_color_code}
Beacons=0
SelfOnly=0
EmbeddedLCOnly=0
DumpTAData=0
CallHang=3
TXHang=4

[P25]
Enable={p25_enable}
Id={p25_id}
NAC={p25_nac}
SelfOnly=0
OverrideUIDCheck=0
RemoteGateway=0
SoftId=0
TXHang=5

[POCSAG]
Enable=0
Frequency={frequency_hz}

[FM]
Enable=0

[DMR Network]
Enable=0

[P25 Network]
Enable=0
"""

    return (
        "\n".join(
            runtime_comments
        )
        + body
    )


def write_mmdvm_host_config(
    output_path: Path,
    protocol: str,
    settings: dict[str, Any],
    *,
    callsign: str,
) -> Path:
    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    rendered = (
        render_mmdvm_host_config(
            protocol,
            settings,
            callsign=callsign,
        )
    )

    temporary_path = (
        output_path.with_suffix(
            ".ini.tmp"
        )
    )

    temporary_path.write_text(
        rendered,
        encoding="utf-8",
    )

    temporary_path.replace(
        output_path
    )

    return output_path
